name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)
parameters:
  - name: 'mavenContainer'
    default: 'maven:3-jdk-11'

# Pipeline triggers on any branch and tag
trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

resources:
  containers:
    - container:  'ubuntu_container_for_build_to_nexus'
      image:      'ubuntu:latest'
    - container:  'postgres'
      image:      'postgres:12-alpine'
      ports:
        - 5432:5432
      env:
        POSTGRES_PASSWORD: postgres
      volumes:
        - pg_sagalog_test:/var/lib/postgresql/data
        - ./init-db-and-user.sql:/docker-entrypoint-initdb.d/init.sql

  repositories:
    - repository: templates
      type:       github
      name:       statisticsnorway/azure-pipelines-templates
      ref:        refs/tags/0.0.7
      endpoint:   statisticsnorway (6)

# Pipeline will be run on this base image
pool:
  vmImage:  'ubuntu-latest'

# Variables global to this pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
variables:

  # Variables defined in Pipelines->Library->Variable Groups in your project in
  # Azure Pipelines
  - group:  Hemmeligheter

  # Variables defined here
  - name:   MAVEN_CACHE_FOLDER
    value:  $(Pipeline.Workspace)/.m2/repository
  - name:   MAVEN_OPTS
    value:  '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

# Job which will run mvn build, mvn install and Sonar Analysis (if branch is master)
jobs:
  - job: buildTest
    displayName:  'compile deploy app'
    container: ${{ parameters.mavenContainer }}

    # Job condition: Run these jobs on any branch, but not on tags
    condition:  not(startsWith(variables['Build.SourceBranch'], 'refs/tags'))

    # Starting a postgres service for testing
    services:
      postgres: postgres

    # Steps in this Job
    steps:

      # Authenticate Maven to Nexus using predefined Service Connections
      # (Project Settings->Pipelines->Service Connections)
      - template: maven/task-authenticate.yml@templates

      # Maven caching to speed up pipeline build time
      - template: maven/task-cache.yml@templates
      - template: maven/task-test-and-verify.yml@templates

      # Sonar-Analyze task to check code test coverage
      - template: maven/task-sonar-analyze.yml@templates

      # Deploy artifact to Nexus
      - template: maven/task-install-and-deploy-to-nexus.yml@templates